archive = "eoan"
version = "19.10"
origin = "system76-natron"
label = "System76 Natron"
email = "info@system76.com"

[[source]]
name = "natron"
build_on = "changelog"
extract = false

    [source.location]
    url = "https://github.com/NatronGitHub/Natron/releases/download/v2.3.14/Natron-2.3.14-Linux-x86_64bit-portable.tar.xz"
    checksum = "f8e860ef081466f9d23d96b7a087efe0416ca06bf3e5428eec70c0b3b8c9752a"
